# This workflow will install Python dependencies, run tests and lint with a variety of Python versions


name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --select=E9,F63,F7,F82 --show-source --statistics
        # run flake8
        flake8 . --show-source --statistics
    - name: Check sorting of dependencies
      run: |
        isort . --check --diff
    - name: Check typing
      run: |
        mypy maldump
    - name: Run simple tests
      run: |
        python -m unittest
        python -m maldump ./test/root
